### PR TITLE
Avoid labels overlaping map

### LINKED ISSUE #86: law_status label overlaps map image when theme title is multiline
In case of a multiline theme title the law_status label is pushed down a bit and overlaps slightly with the map image:
title_overlap

This does not like nice and i suppose in case of a threeline theme title the overlap would be even bigger.

### PR DESCRIPTION
**Pull request by marionb**
This fixes #86

### CODE REVIEW

**Comment by jwkaltz** [comment]
Are we sure about the font size @voisardf ? Here a change from 8.5 to 8 is proposed, but I remember this pr https://github.com/openoereb/pyramid_oereb/issues/297, where it was written " The font and the font size of the legend entries should be Cadastra 8.5 pt everywhere"

**Comment by voisardf** [comment]
It's why I asked @marionb to check during the meeting (I think you already had left). 
I know that font sizes were changed in the new specs (p.22 ff), 
Looks like the title font size is now 15pt and legal status is 8pt as is standard text. So 8pt is fine 👍

**Comment by jwkaltz** [comment]
Ah OK, thanks.
(I didn't realize the extracts are meant for reading only for young people, with good eyes ;) )

**Comment by voisardf** [comment]
https://www.cadastre.ch/de/manual-oereb/service/extract/static.html

**Review by jwkaltz — APPROVED** [review]

**Comment by voisardf** [comment]
> Ah OK, thanks. (I didn't realize the extracts are meant for reading only for young people, with good eyes ;) )

it would seem so... 😉

**Comment by marionb** [comment]
Yes @jwkaltz I checked the font size and compared them with the spec and for this part the standard is 8 that is why I changed it ;-). It did not change much though because most of it had already been changed.
I'll merge this or do you want more time to test it @voisardf ?

**Comment by voisardf** [comment]
@marionb : I'm testing it right now

**Review by voisardf — APPROVED** [review]
No more overlapping, thanks. 
Could you just verify it's 12mm between the topic title bottom and the map frame - I think I have no means here to check.

**Comment by marionb** [comment]
It should be 12mm. I printed it on paper and measured it as well as I could :-D

**Comment by voisardf** [comment]
> It should be 12mm. I printed it on paper and measured it as well as I could :-D

perfect! 👍

**Pull request merged**
