### PR TITLE
Toc calculations

### PR DESCRIPTION
**Pull request by voisardf**
This version of the templates adapts the line heights and spacings in the TOC page and the associated subreports where different field sizes have been defined. 
TOC calculations should be simplified this way and the pdf creation should still work as expected

- [x] For the theme list in detail 2 band the TOC was defined by a height of 17px, but the subreport has a min height of 20px
- [x] For the detail 3 band, the subreport had a initial height of 15px whereas the subreport only has a height of 12px
- [x] For the detail 5, we defined a min height of 93px - probably to ensure the general information part (detail 6) is pushed at the bottom of the page or on a new page. But the specification mentions nothing about that alignement. So I adjusted the spacing between detail 5 and 6 to 1cm
This leads to a lot more of the PDF's with only one TOC page in our case.

new:
TOC_adapted_spacing_line_heights

[20241025085449_extract.pdf](https://github.com/user-attachments/files/17519993/20241025085449_extract.pdf)

before:
TOC_default_1line_for_d1_77px

[66aca8c4-101f-4b40-b6ab-b1841f111be5.pdf](https://github.com/user-attachments/files/17519996/66aca8c4-101f-4b40-b6ab-b1841f111be5.pdf)

You may wan't to try this branch of mfp with the toc_calculations branch: PR https://github.com/openoereb/pyramid_oereb/pull/2047

### CODE REVIEW

**Comment by michmuel** [comment]
I think it is not ideal to have a heading without an item. I would appreciate something like "None", but I guess that is not supported by Swisstopo.

oereb-print-image-1

**Comment by voisardf** [comment]
This is probably the reason why we had the larger spacing at the bottom of the page. - We could potentially print à "-" to indicate that there are no themes in this category. Or we increase the spacing to 2cm.
Probably the better choice would be the indication that none are concerned ("-")

**Comment by michmuel** [comment]
> This is probably the reason why we had the larger spacing at the bottom of the page. - We could potentially print à "-" to indicate that there are no themes in this category. Or we increase the spacing to 2cm. Probably the better choice would be the indication that none are concerned ("-")

The dash sounds good to me as we have this element already in use at "Übrige Legende (im sichtbaren Bereich)" for the case of no items.

**Review by svamaa — COMMENTED** [review]
I did test the branch within our environment. However, table of contents page did not change. The block around the general information and QR Code are all on the second page.
Maybe we'll need more testing from other cantons?

**Comment by voisardf** [comment]
@svamaa depending on the number of themes, that is possible. More testing is always helpful 👍
did you make a clean testing instance (delete oereb base images)

**Comment by lopo977** [comment]
This is our (TI) PDF output with this #147 merged.
I choose a parcel with some themes.
[20241104110131_extract.pdf](https://github.com/user-attachments/files/17617148/20241104110131_extract.pdf)

**Review by michmuel — CHANGES_REQUESTED** [review]
I suggest to insert a dash if no entries exist for a section.

**Comment by lopo977** [comment]
camptocamp/mapfish_print:3.30.11 still buggy in some cases, but lgtm.

**Review by lopo977 — APPROVED** [review]
camptocamp/mapfish_print:3.30.11 still buggy in some cases, but lgtm.

**Comment by voisardf** [comment]
@michmuel @svamaa @peterschaer I added the dash for an empty section. If it works for you, we can merge this part and also the corresponding PR https://github.com/openoereb/pyramid_oereb/pull/2047

**Comment by michmuel** [comment]
Thanks @voisardf for the update. The dash looks good.

I was wondering how it looks if no oereb topic has restrictions relevant for a real estate. An example can be found here: https://oereb.geo.bl.ch/extract/pdf/?egrid=CH611208837859. I can not find the expression "Es existieren keine Themen für dieses Grundstück." in  the [swisstopo specs](https://backend.cadastre-manual.admin.ch/fileservice/sdweb-docs-prod-cadastremanch-files/files/2024/03/07/4e7edcc6-897d-40b4-ae1b-db6c76669d56.pdf). Shall we leave that as it is or change both to dashes or change both to "Keine Themen"?

**Comment by voisardf** [comment]
@michmuel I would leave the text for this section and case.

**Comment by peterschaer** [comment]
> Thanks @voisardf for the update. The dash looks good.
> 
> I was wondering how it looks if no oereb topic has restrictions relevant for a real estate. An example can be found here: https://oereb.geo.bl.ch/extract/pdf/?egrid=CH611208837859. I can not find the expression "Es existieren keine Themen für dieses Grundstück." in the [swisstopo specs](https://backend.cadastre-manual.admin.ch/fileservice/sdweb-docs-prod-cadastremanch-files/files/2024/03/07/4e7edcc6-897d-40b4-ae1b-db6c76669d56.pdf). Shall we leave that as it is or change both to dashes or change both to "Keine Themen"?

The text you are looking for is not in the spec but in the accompanying XML file: https://www.cadastre-manual.admin.ch/de/rahmenmodell-oereb-kataster (at the bottom of the page). 

In german it's `ÖREB-Kataster für dieses Grundstück nicht verfügbar`. In my opinion, however, it is not a particularly accurate text.

**Comment by michmuel** [comment]
> > Thanks @voisardf for the update. The dash looks good.
> > I was wondering how it looks if no oereb topic has restrictions relevant for a real estate. An example can be found here: https://oereb.geo.bl.ch/extract/pdf/?egrid=CH611208837859. I can not find the expression "Es existieren keine Themen für dieses Grundstück." in the [swisstopo specs](https://backend.cadastre-manual.admin.ch/fileservice/sdweb-docs-prod-cadastremanch-files/files/2024/03/07/4e7edcc6-897d-40b4-ae1b-db6c76669d56.pdf). Shall we leave that as it is or change both to dashes or change both to "Keine Themen"?
> 
> The text you are looking for is not in the spec but in the accompanying XML file: https://www.cadastre-manual.admin.ch/de/rahmenmodell-oereb-kataster (at the bottom of the page).
> 
> In german it's `ÖREB-Kataster für dieses Grundstück nicht verfügbar`. In my opinion, however, it is not a particularly accurate text.

Thanks @peterschaer for the hint. I agree with you that the text in the xml is not optimal. @voisardf I think we can leave it unchanged.

**Review by michmuel — APPROVED** [review]

**Pull request merged**
