### PR TITLE
#128: Lawstatus in TOC printed conditionally (only if not inForce)

### LINKED ISSUE #128: Status "rechtskräftig" should not be printed in the TOC
According to the instruction (p. 14), the status of a theme has to be indicated in the TOC only if it is a change:

> Falls ein ÖREB in Änderung angegeben wird, dann ist anschliessend auf derselben Zeile das ÖREB-Thema ergänzt mit dem Text «Änderung mit Vorwirkung» respektive «Änderung ohne Vorwirkung» anzugeben.

Therefore the status "Rechtskräftig" should not be printed in the TOC.

### PR DESCRIPTION
**Pull request by peterschaer**
fixes #128

### CODE REVIEW

**Comment by voisardf** [comment]
@peterschaer I don't recall it right now and would have to check: is the code always in english now or does it depend on the local configuration in the yaml?

**Comment by peterschaer** [comment]
In the instruction (Data Extract) it is always in english (inForce, changeWithPreEffect, changeWithoutPreEffect). It can be changed in the yaml-configuration but that would violate the instruction.

**Review by voisardf — APPROVED** [review]
ok, thanks for the heads up. Then it's fine. Code looks good to me

**Review by michmuel — APPROVED** [review]
Looks good to me.

**Pull request merged**
