### PR TITLE
fix multi-page TOC related numbering issue

### PR DESCRIPTION
**Pull request by danduk82**
this is the corresponding PR to this one in [pyramid_oereb](https://github.com/openoereb/pyramid_oereb/pull/983) to fix the numbering problem in table of content when TOC is longer than 1 page.

**BREAKING CHANGE:** It also removes the multi page TOC features, because they are not standard and not needed anymore

### CODE REVIEW

**Review by marionb — CHANGES_REQUESTED** [review]
@danduk82 can you rebase this to the current master status. At the moment is it breaking some URLs in the topic page but I think it is just a re-base issue. Other than that this looks good to me.
TANKS !

**Comment by danduk82** [comment]
@marionb ok I do it now

**Comment by danduk82** [comment]
@marionb I have rebased and force-pushed. But this has deleted your remarks in commits of the review.

Do you still have remarks?

**Review by marionb — APPROVED** [review]
This looks good. There are no comments missing ;) .
In my opinion you can merge this and the corresponding PR from pyramid_oereb.

**Comment by danduk82** [comment]
FYI here is the [related issue](https://github.com/openoereb/pyramid_oereb_mfp/issues/48) in `pyramid_oereb_mfp`

**Review by jwkaltz — APPROVED** [review]

**Pull request merged**
