### PR TITLE
added header in header band for multipage glossary

### PR DESCRIPTION
**Pull request by voisardf**
Title says it all.
merge previous PR's first.

fixes:
- [x] issue: https://github.com/openoereb/pyramid_oereb_mfp/issues/20 - header missing on multipage glossary

### CODE REVIEW

**Review by marionb — APPROVED** [review]
LGTM

**Review by vvmruder — APPROVED** [review]
Nice solution

**Review by jwkaltz — APPROVED** [review]
Feel free to merge (I trust @marionb 's Jasper skills more than mine...)

**Review by kdeininger — APPROVED** [review]

**Comment by voisardf** [comment]
merging

**Pull request merged**
