### PR TITLE
#126: fix font-size of legend labels

### LINKED ISSUE #126: Font size of legend labels too large
The font size of the legend labels (other legend and concerned legend) is too large. Instead of 9 pt, it must be 8 pt (see instruction p. 28).

### PR DESCRIPTION
**Pull request by peterschaer**
fixes #126

### CODE REVIEW

**Comment by michmuel** [comment]
Thanks for correcting! There is a vertical displacement between the symbol and the legend text. Do you agree? Could the alignment be improved? With smaller font size it is more apparent.

**Review by voisardf — APPROVED** [review]
thanks!

**Comment by peterschaer** [comment]
> Thanks for correcting! There is a vertical displacement between the symbol and the legend text. Do you agree? Could the alignment be improved? With smaller font size it is more apparent.

Yes, I can see that too. I tried optimize the vertical placement. At least on my side it looks better now.

**Review by michmuel — APPROVED** [review]
Yes, I agree, it is better now. Thanks!

**Pull request merged**
