### PR TITLE
#129: remove municipality name from header

### LINKED ISSUE #129: Municipality logo without name
According to the instruction (p. 11 and 26), only the logos and no texts are output in the header. This means that the name of the municipality below the municipality logo must be deleted.

### PR DESCRIPTION
**Pull request by peterschaer**
fixes #129

### CODE REVIEW

**Comment by michmuel** [comment]
The name of the municipality below the coat of arms (right expression?) might not be according to the specs (except it can be considered as a component of it). My first impression is that it is better to have it. Municipality name is written only on the first page. And not everyone is that familiar with all the coat of arms.

**Comment by voisardf** [comment]
According to the specs, the municipality name is indeed not mandatory. I do agree with @michmuel that it could be nice to keep it - but should we render it optional?

**Comment by peterschaer** [comment]
I realise that the name of the municipality has its justification. I wonder if it is worth the effort to make it optional. That would also affect the print_proxy in pyramid_oereb, wouldn't it? For me, it's enough if I can delete or comment out the corresponding code block in our own repository.

**Comment by jwkaltz** [comment]
> I realise that the name of the municipality has its justification. I wonder if it is worth the effort to make it optional. That would also affect the print_proxy in pyramid_oereb, wouldn't it? For me, it's enough if I can delete or comment out the corresponding code block in our own repository.

Yes, it would require a configuration parameter in pyramid_oereb itself,
but that is not a big deal, as we already have a couple of examples for that.
I would prefer that to customizing the print templates per project (the goal is that each project can use the templates out-of-the-box, without modification).
I can assist with adding this as an option in pyramid_oereb, if desired.

**Comment by voisardf** [comment]
I'm also fan of the optional parameter even if this means a little more work (now).

**Comment by peterschaer** [comment]
That is also ok for me. An optional parameter is certainly the more consistent solution.

**Comment by jwkaltz** [comment]
> That is also ok for me. An optional parameter is certainly the more consistent solution.

Do you want to do a pull request for that, or shall I?

**Comment by peterschaer** [comment]
Could you do the pull request? This is beyond my mapfish_print knowledge ;-)

**Comment by peterschaer** [comment]
is replaced by #132

**Pull request closed without merging**
