### PR TITLE
96-label-flaeche

### LINKED ISSUE #96: Label "Fläche" is missing on title page
The label "Fläche" is missing on the first page of the document. Only the numeric value of the area is printed on the right side of the specific line. Vertical space between "Fläche" and "Stand der amtlichen Vermessung" too large.

[CH107812348389_comments.pdf](https://github.com/openoereb/pyramid_oereb_mfp/files/8349437/CH107812348389_comments.pdf)

Specs:

https://www.cadastre.ch/content/cadastre-internet/de/manual-oereb/service/extract/static/_jcr_content/contentPar/tabs_copy_copy_copy_/items/dokumente/tabPar/downloadlist/downloadItems/426_1475413822017.download/Weisung-statischer-Auszug-de.pdf

### PR DESCRIPTION
**Pull request by michmuel**
fix https://github.com/openoereb/pyramid_oereb_mfp/issues/96

### CODE REVIEW

**Comment by jwkaltz** [comment]
Thanks @michmuel is it OK if we wait for Marion's return for the review? 
I would feel more confident.

**Comment by michmuel** [comment]
That's fine. Maybe she knows if it is possible to define a variable for the position offset to improve the readability (fewer repetitions of the same code).

**Review by marionb — CHANGES_REQUESTED** [review]
@michmuel yes I agree that at the moment there are too many repetitions of the same text fields that will be very difficult to maintain and also read.
I don't yet see why the template changes this much with this parameter `Display_RealEstate_SubunitOfLandRegister`?
So it is not only the `Area` parameter that disappears?

**Comment by michmuel** [comment]
@marionb 
If Display_RealEstate_SubunitOfLandRegister==False the respective row is not displayed. This causes a change of the vertical position of the row with the area information, and, according to the specs, also a vertical shift of all elements below. See: https://www.cadastre.ch/content/cadastre-internet/de/manual-oereb/publication/instruction.download/cadastre-internet/de/documents/oereb-weisungen/Weisung-statischer-Auszug-de.pdf

I am wondering if something like this works (conceptually described):

```
if Display_RealEstate_SubunitOfLandRegister
    delta_vertical_pos = 0
else
   delta_vertical_pos = y_offset
...
<reportElement x="0" y="540+delta_verical_pos" width="493" height="17" uuid="22ad5f4f-d1eb-4eef-ad76-4458ea1734df">

```

So, the code would not have to be duplicated. But maybe, there is no such option.

**Comment by marionb** [comment]
OK I currently am looking at a version using. I think the easiest is to use two different sub-reports (using only one subreport unfortunately will not work for that we will probably have to restructure how the data comes in from pyramid_oereb and that will cost too much time to do). 
The best is to do something similar to what we already have for the tittle. Like this there will still be a lot of code duplication but it will be easier to read and hopefully understand ;-)
I'll make a commit with a suggestion.

**Pull request closed without merging**
